language: objective-c
osx_image: xcode7.1
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - gem update
    - brew update
xcode_workspace: MHImportBuster.xcworkspace
xcode_scheme: Peckham
